# fly.toml file generated for igit on 2022-08-19T11:09:40+08:00

app = "igit"
kill_signal = "SIGINT"
kill_timeout = 6

[build]
image = "gitea/gitea:latest"

[[mounts]]
destination = "/data"
source = "data"

[[services]]
internal_port = 22
protocol = "tcp"

[[services.ports]]
port = 22

[[services]]
internal_port = 3000
protocol = "tcp"

[[services.ports]]
force_https = true
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443
